2021-03-26 14:20:28,729 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:23:03,078 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:23:03,135 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:23:03,178 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:23:03,231 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:30:36,979 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:30:37,011 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:30:37,080 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 14:30:37,163 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:42:13,049 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:42:13,098 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:42:13,126 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:42:13,212 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:42:15,323 ERROR: Exception on /get_billing_settings [POST] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'payment__breakpoint.due_on_receipt' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/hdd/code/eastbournecottage/app/routes.py", line 552, in get_billing_settings
    db_payment_breakpoints = settings_query.payment_breakpoints
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 287, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 723, in get
    value = self.callable_(state, passive)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 759, in _load_for_state
    return self._emit_lazyload(
  File "<string>", line 1, in <lambda>
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 900, in _emit_lazyload
    q(session)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 545, in all
    return list(self)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 445, in __iter__
    return q._execute_and_instances(context)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1127, in _execute_clauseelement
    ret = self._execute_context(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    self._handle_dbapi_exception(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    util.raise_(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    self.dialect.do_execute(
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'payment__breakpoint.due_on_receipt' in 'field list'")
[SQL: SELECT payment__breakpoint.id AS payment__breakpoint_id, payment__breakpoint.billing_settings_id AS payment__breakpoint_billing_settings_id, payment__breakpoint.amount_due AS payment__breakpoint_amount_due, payment__breakpoint.due_by AS payment__breakpoint_due_by, payment__breakpoint.due_on_receipt AS payment__breakpoint_due_on_receipt, payment__breakpoint.is_percentage AS payment__breakpoint_is_percentage, payment__breakpoint.is_absolute AS payment__breakpoint_is_absolute 
FROM payment__breakpoint 
WHERE %(param_1)s = payment__breakpoint.billing_settings_id]
[parameters: {'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2021-03-26 16:43:24,010 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:43:24,077 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:43:24,087 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:43:24,181 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:44:39,999 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:44:40,069 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:44:40,147 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:44:40,154 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:45:44,800 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:45:44,879 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:45:44,890 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-03-26 16:45:44,959 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
