2021-04-12 13:38:01,229 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 13:38:47,540 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 13:38:47,566 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 13:38:47,625 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 13:38:47,685 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 16:44:49,215 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 16:44:49,249 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 16:44:49,319 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 16:44:49,381 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 16:44:51,066 ERROR: Exception on /admin [GET] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 270, in decorated_view
    elif not current_user.is_authenticated:
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "/hdd/code/eastbournecottage/app/models.py", line 8, in load_user
    return User.query.get(int(id))
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/base.py", line 451, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/base.py", line 430, in _inspect_mapped_class
    mapper._configure_all()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1354, in _configure_all
    configure_mappers()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 3280, in configure_mappers
    mapper._post_configure_properties()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1967, in _post_configure_properties
    prop.init()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/interfaces.py", line 197, in init
    self.do_init()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2080, in do_init
    self._generate_backref()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2329, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'linked_invoice' on relationship 'Billing.linked_payments': property of that name exists on mapper 'mapped class Billing->billing'
2021-04-12 17:01:53,356 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 17:01:53,438 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 17:01:53,455 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 17:01:53,485 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 17:01:55,992 ERROR: Exception on /admin [GET] [in /hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 270, in decorated_view
    elif not current_user.is_authenticated:
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/utils.py", line 346, in _get_user
    current_app.login_manager._load_user()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_login/login_manager.py", line 318, in _load_user
    user = self._user_callback(user_id)
  File "/hdd/code/eastbournecottage/app/models.py", line 8, in load_user
    return User.query.get(int(id))
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 512, in __get__
    mapper = orm.class_mapper(type)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/base.py", line 451, in class_mapper
    mapper = _inspect_mapped_class(class_, configure=configure)
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/base.py", line 430, in _inspect_mapped_class
    mapper._configure_all()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1354, in _configure_all
    configure_mappers()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 3280, in configure_mappers
    mapper._post_configure_properties()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1967, in _post_configure_properties
    prop.init()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/interfaces.py", line 197, in init
    self.do_init()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2080, in do_init
    self._generate_backref()
  File "/hdd/code/eastbournecottage/venv/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 2329, in _generate_backref
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Error creating backref 'linked_invoice' on relationship 'Billing.linked_payments': property of that name exists on mapper 'mapped class Billing->billing'
2021-04-12 17:03:56,517 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 17:03:56,569 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 17:03:56,636 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
2021-04-12 17:03:56,742 INFO: eastbourne startup [in /hdd/code/eastbournecottage/app/__init__.py:29]
